### ISSUE TITLE
Generated typescript code producing errors

### ISSUE THREAD

**Issue by stifflerus** [metadevpro/ts-pegjs#19] opened 2018-05-29 20:11 UTC
This is for v0.1.14

The generated typescript code is produces the following errors when compiled (parser.ts is the output of pegjs):

`
parser.ts(49,40): error TS4070: Parameter 'expected' of public static method from exported class has or is using private name 'Expectation'.
`

`
parser.ts(140,20): error TS4031: Public property 'expected' of exported class has or is using private name 'Expectation'.
`

`
parser.ts(145,42): error TS4063: Parameter 'expected' of constructor from exported class has or is using private name 'Expectation'.
`

This happens no matter what grammar I specify in my .pegjs file. For example, the errors occur with a trivial grammar such as
`
trivial
  = 'x'
`

The error seems to stem from generated types `Expectation`, `IOtherExpectation`, `IEndExpectation`, `IAnyExpectation`, `IClassExpectation`, `IClassParts`, and `ILiteralExpectation` not being exported from the generated parser source file. I can fix this manually to remove the errors but ts-pegjs should not be generating them in the first place.

ts-pegjs: 0.1.14
typescript: 2.8.3
pegjs: 0.10.0

**Comment by pjmolina** [comment] 2018-05-29 22:22
Thanks for reporting @stifflerus  
Duplicate of #18  Tracking the issue there. 
Need more info to reproduce the conditions to make evident the bug.

**Closed** 2018-05-29 22:39 UTC
Labels: bug, duplicate
